from numpy import float64
from numpy.typing import NDArray

_AVOID_DIVIDE_BY_ZERO: float64

class _A:
    def __getitem__(self, key: object) -> NDArray[float64]: ...

A: _A

def sqrt_nan(n: NDArray[float64]) -> NDArray[float64]: ...
def dots(v: NDArray[float64], u: NDArray[float64]) -> NDArray[float64]: ...
def T(M: NDArray[float64]) -> NDArray[float64]: ...
def mxv(M: NDArray[float64], v: NDArray[float64]) -> NDArray[float64]: ...
def mxm(M1: NDArray[float64], M2: NDArray[float64]) -> NDArray[float64]: ...
def mxmxm(M1: NDArray[float64], M2: NDArray[float64], M3: NDArray[float64]) -> NDArray[float64]: ...

_T = T
_mxv = mxv
_mxm = mxm
_mxmxm = mxmxm

def length_of(xyz: NDArray[float64]) -> NDArray[float64]: ...
def angle_between(u: NDArray[float64], v: NDArray[float64]) -> NDArray[float64]: ...
def to_spherical(xyz: NDArray[float64]) -> tuple[NDArray[float64], NDArray[float64], NDArray[float64]]: ...
def _to_spherical_and_rates(
    r: NDArray[float64], v: NDArray[float64],
) -> tuple[NDArray[float64], NDArray[float64], NDArray[float64], NDArray[float64], NDArray[float64], NDArray[float64]]: ...
def from_spherical(r: NDArray[float64], theta: NDArray[float64], phi: NDArray[float64]) -> NDArray[float64]: ...

to_polar = to_spherical
from_polar = from_spherical

def rot_x(theta: NDArray[float64]) -> NDArray[float64]: ...
def rot_y(theta: NDArray[float64]) -> NDArray[float64]: ...
def rot_z(theta: NDArray[float64]) -> NDArray[float64]: ...
def R1(theta: NDArray[float64]) -> NDArray[float64]: ...
def R2(theta: NDArray[float64]) -> NDArray[float64]: ...
def R3(theta: NDArray[float64]) -> NDArray[float64]: ...
def angular_velocity_matrix(angular_velocity_vector: NDArray[float64]) -> NDArray[float64]: ...
def _to_array(value: object) -> NDArray[float64] | float64: ...
def _reconcile(a: NDArray[float64], b: NDArray[float64]) -> tuple[NDArray[float64], NDArray[float64]]: ...
def load_bundled_npy(filename: str) -> NDArray[float64]: ...
